"""Tests for inject_customize.py — bmad-code-review merge mode (issue #18).

BCP hooks into bmad-code-review's on_complete to auto-trigger recalibrate
after each reviewed story. Because PULSE may already own that file, the
injection must APPEND (merge mode) rather than overwrite.
"""
from __future__ import annotations

import hashlib
from pathlib import Path

import pytest

from .conftest import REPO_ROOT, SKILLS, run_script

TEMPLATE = (SKILLS / "bmad-bcp-setup/assets/customize-templates"
            / "bmad-code-review.toml")
GOLDEN_STANDALONE = REPO_ROOT / "tests/fixtures/golden/customize-bmad-code-review.toml"
GOLDEN_MERGED = REPO_ROOT / "tests/fixtures/golden/customize-bmad-code-review-merged.toml"
INJECT = SKILLS / "bmad-bcp-setup/scripts/inject_customize.py"

BCP_SENTENCE = "BCP auto-recalibrate: após o code review encerrar"

# Simulates what PULSE writes to _bmad/custom/bmad-code-review.toml
PULSE_FILE_CONTENT = '''\
# PULSE auto-tracking — track-done hook
#
# This file is generated by `bmad-pulse-setup`.

[workflow]

on_complete = "PULSE auto-tracking: invoke the bmad-pulse-track-done skill, passing the story_id of the just-reviewed story as argument (e.g. /bmad-pulse-track-done 15.3). The skill records end_ts, calculates the AI Leverage Ratio, and displays the Efficiency Pulse. It will interactively prompt for review_cycles and (optionally) effective_hours — wait for the user's response. Pre-requisite: a start_ts must exist in pulse_metrics: for this story (recorded by bmad-dev-story); if absent, the skill warns and suggests running track-start first."
'''


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _pulse_dest(tmp_path: Path) -> Path:
    """Create a PULSE-owned bmad-code-review.toml in tmp_path."""
    dest_dir = tmp_path / "_bmad/custom"
    dest_dir.mkdir(parents=True)
    dest = dest_dir / "bmad-code-review.toml"
    dest.write_text(PULSE_FILE_CONTENT, encoding="utf-8")
    return dest


def test_template_matches_golden_standalone():
    assert _sha(TEMPLATE) == _sha(GOLDEN_STANDALONE), (
        "bmad-code-review template drifted from its golden snapshot. "
        "Refresh tests/fixtures/golden/customize-bmad-code-review.toml "
        "in the same PR so the hook surface stays reviewed."
    )


def test_inject_creates_file_when_no_existing(tmp_path):
    """No existing file → plain copy from template."""
    proc = run_script(INJECT, "--project-root", str(tmp_path),
                      "--skill", "bmad-code-review")
    assert proc.returncode == 0, proc.stderr
    dest = tmp_path / "_bmad/custom/bmad-code-review.toml"
    assert dest.exists()
    assert BCP_SENTENCE in dest.read_text(encoding="utf-8")


def test_inject_merge_appends_to_existing_on_complete(tmp_path):
    """PULSE file already exists → BCP sentence appended to on_complete."""
    dest = _pulse_dest(tmp_path)

    proc = run_script(INJECT, "--project-root", str(tmp_path),
                      "--skill", "bmad-code-review")
    assert proc.returncode == 0, proc.stderr

    merged_text = dest.read_text(encoding="utf-8")
    assert "PULSE auto-tracking" in merged_text, "PULSE sentence lost after merge"
    assert BCP_SENTENCE in merged_text, "BCP sentence missing after merge"
    assert merged_text.count("on_complete") == 1, "should have single on_complete key"


def test_inject_merge_matches_golden(tmp_path):
    """Merged output matches the golden snapshot."""
    dest = _pulse_dest(tmp_path)

    proc = run_script(INJECT, "--project-root", str(tmp_path),
                      "--skill", "bmad-code-review")
    assert proc.returncode == 0, proc.stderr
    assert _sha(dest) == _sha(GOLDEN_MERGED), (
        "Merged output != golden snapshot. If the change is intentional, "
        "refresh tests/fixtures/golden/customize-bmad-code-review-merged.toml."
    )


def test_inject_merge_is_idempotent(tmp_path):
    """Running inject twice must not modify the file on second run."""
    dest = _pulse_dest(tmp_path)

    run_script(INJECT, "--project-root", str(tmp_path), "--skill", "bmad-code-review")
    first_sha = _sha(dest)

    proc2 = run_script(INJECT, "--project-root", str(tmp_path),
                       "--skill", "bmad-code-review")
    assert proc2.returncode == 1, "second run should exit 1 (already-present)"
    assert _sha(dest) == first_sha, "file mutated on second run — idempotency broken"


def test_inject_merge_no_duplicate_bcp_sentence(tmp_path):
    """BCP sentence appears exactly once after two runs."""
    dest = _pulse_dest(tmp_path)

    run_script(INJECT, "--project-root", str(tmp_path), "--skill", "bmad-code-review")
    run_script(INJECT, "--project-root", str(tmp_path), "--skill", "bmad-code-review")

    text = dest.read_text(encoding="utf-8")
    assert text.count(BCP_SENTENCE) == 1, "BCP sentence duplicated"


def test_inject_standalone_bcp_only(tmp_path):
    """BCP-only file (no PULSE): standalone content matches golden."""
    proc = run_script(INJECT, "--project-root", str(tmp_path),
                      "--skill", "bmad-code-review")
    assert proc.returncode == 0, proc.stderr
    dest = tmp_path / "_bmad/custom/bmad-code-review.toml"
    assert _sha(dest) == _sha(GOLDEN_STANDALONE)
